<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles.css">
    <title>Pravallika - Portfolio</title>
</head>
<body>
    <!-- Your content goes here -->
    <header>
        <h1>Pravallika</h1>
        <p>Web Developer</p>
    </header>

    <nav>
        <ul>
            <li><a href="about">About Me</a></li>
            <li><a href="portfolio">Portfolio</a></li>
            <li><a href="contact">Contact</a></li>
        </ul>
    </nav>

    <section id="about">
        <h2>Name:Pravallika</h2>
    </section>

    <section id="portfolio">
        <h2>Portfolio</h2>
    </section>

    <section id="contact">
        <h2>contact:8019XXXXXX</h2>
</section>
<section id="hobbies">
<h2>Hobbies<h2>
<ul>
<li>Reading</li>
<li>Painting</li>
<li>listening Music</li>
</ul>

    </section>
<section id="accomplishments">

<h2>Accomplishments<h2>
    <ul>
<li>One of the member of the Street Cause</li>
<li>Achieved Silver medal on the occassion of Academic Execellence<li>
</ul>

    <footer>
        <p>&copy; 2023 Pravallika</p>
    </footer>
</body>
<style>
body {
    font-family: 'Arial', sans-serif;
    margin: 0;
    padding: 0;
}

header {
    background-color: #333;
    color: #fff;
    text-align: center;
    padding: 20px;
}

nav {
    background-color:aquamarine;
    color: black;
    padding: 10px;
    
}

nav ul {
    list-style: none;
    margin: 0;
    padding: 0;
}

nav li {
    display: inline;
    margin-right: 400px;
}

nav a {
    text-decoration: none;
    color: #fff;
}

section {
    padding: 20px;
}

footer {
    background-color: #333;
    color: #fff;
    text-align: center;
    padding: 10px;
    position: fixed;
    bottom: 0;
    width: 100%;
}
</style>
</html>
